### ISSUE TITLE
Using JSON Schema

### ISSUE THREAD

**Issue by Bosek** [Bosek/pluginloader#2]
http://www.newtonsoft.com/jsonschema

For better convenience working with `plugin.json` and validation maybe?

**Comment by Zinal001** [comment]
Might be a good idea.
While on the subject of ```plugin.json```, I'm guessing the documentation on the [example plugins](https://github.com/Bosek/pluginloader/blob/master/Example%20Plugins/Python/README.md) are wrong about the structure of a dependency?

**Comment by Bosek** [comment]
Yeah. It's a while since I worked on it. As far as I remember, you have to specify UniqueName and Version, while only major and minor version number is checked against plugin version(actual version has to be higher or equal to required). It definitelly needs some more documenting.

If you feel it can work differently, I'll be happy to merge more PRs :P

**Comment by Bosek** [comment]
[http://semver.org/](semver)

PL is already using it, We just need proper parser, because as far as I know, .NET Version does not support parsing strings(in case of 1.0.0-alpha). I'll take a look when I'm done with launcher.

**Comment by Bosek** [comment]
Closing. I think that using SCHEMA would be overkill right now. We store minimal data in JSON.
