### ISSUE TITLE
Patcher or launcher?

### ISSUE THREAD

**Issue by Bosek** [Bosek/pluginloader#4]
It should be possible to create launcher-based PL, instead of patcher-based. But what is the best way?

Launcher would be a bit more user-friendly and probably easier to maintain, since we wouldn't have to write PatcherGUI wizard. On the other hand it needs some redesign in order to work.

Patcher might be problematic, because users have to patch everytime game updates. Plus we have to develop PatcherGUI. (it also needs some more work, but not that much as launcher mechanism)

My personal opinion is, that Launcher is a bit more elegant. Rework just would take some time I could spend on enhancing API and polishing code. Also, it's better to do rework sooner than later, so we don't break potential mods in future.

**Comment by Zinal001** [comment]
Launcher all the way!
I know the frustration of starting up a server only to realize that the game has been updated, so no plugins.
Sure, it will take some time to make the launcher but as you said, better to do rework sooner than later ;)

**Comment by Bosek** [comment]
I've done some work on it but then I realized - what about Steam? Players usually start the game from Steam. So what now? You can create Steam shortcut, but is it really that convenience level we are striving for?

**Comment by Zinal001** [comment]
Well.. Wouldn't it be possible to patch in a launcher at the constructor of IR.exe?
Like, if IR.exe is missing an argument (Ex. -launched) then start the launcher in another process and then exit IR.exe?

**Comment by Bosek** [comment]
But that would still need patching IR.exe, right? So if you update with Steam, you have to repatch.

The thing is, that if you want to run the game via Steam, you need to launch IR.exe. And if the game updates, IR.exe is updated. This means that you cannot edit IR.exe if you want PL to "just work" after game update.

**Comment by Zinal001** [comment]
Right!
Well, I guess a standalone launcher is the only way to proceed, unless you want to make a service that checks IR.exe once in a while and patches it if it doesn't hasn't been already (I would not recommend this approach however).

**Comment by Bosek** [comment]
So we will have flow like this:
download PL -> unpack to IR folder -> run game via launcher
instead of
download PL -> unpack to IR folder -> patch the game -> run via IR.exe

First one doesn't need repatching, but game has to be started with launcher.
Second one needs patch every time game updates, but can be started with IR.exe(thus via Steam).

I am still not sure though. I think that not being able to run game with default Steam shortcut is significant drawback especially for users with lower IT skills. What do you think?

**Comment by Zinal001** [comment]
> ~~download PL -> unpack to IR folder -> run game with launcher~~
I think the way to go is:
Download PL -> Install PL -> Run game with launcher.

Creating an installer for PL would help users with lower IT skills, since installers can easily create shortcuts and stuff.

Also, the best thing about a launcher is that users can play the game without patching if needed.

**Comment by Bosek** [comment]
So we still need some kind of installer.

**Comment by Zinal001** [comment]
I have access to a program called **Advanced Installer** but I'll have to check the license to see if we can use it.

**Comment by Bosek** [comment]
We can use something much more basic.
Theoretical flow:
![pl installer flow 1](https://cloud.githubusercontent.com/assets/6001235/20919773/bfa12006-bb9d-11e6-8e26-f388bf2b1aea.png)

I guess this would be more than enough. Without writing into registry etc. And we wouldn't have to redistribute latest versions of PL. Everytime someone runs installer, it will check GIT version and eventually download and install latest. We can also add version check to PL itself, which will just advice users to run installer and update PL this way.

**Comment by Zinal001** [comment]
I like it!
I think the installer should backup the files that it overwrites in the game directory and have an option to restore the original files (just in case).

Also, the "Ask for game path" step could theoretically get the game installation path by looking in the registry. --> "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Steam App 363360"

**Comment by Bosek** [comment]
PL doesn't need to overwrite any files 😈 

Launcher will create `patchedIR.exe` upon every launch. This file can be used for PL developing(since you need patched executable) or directly running IR with PL.

Basically it will work similarly as patcher did, it's no-go because of how assemblies are handled in .NET. Running with launcher just guarantees always patched executable because it regenerates patchedIR.exe and runs it directly. It's a bit quicker however, because launcher wouldn't need to extract all additional files like IPY libs and dlls.

At the end we will technically provide both options - patcher and launcher.

> Also, the "Ask for game path" step could theoretically get the game installation path by looking in the registry. --> "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Steam App 363360"

Good hint. I'll definitelly look into it :)

**Comment by Bosek** [comment]
I've made simple RunKit API for installer,
Installer will send GET request to https://runkit.io/bosek/pluginloader-installer-api/branches/master
Download ZIP(not TAR) and do steps described above.

**Comment by Zinal001** [comment]
Ah, I see. I just didn't want to patch the original IR.exe, but if a patchedIR.exe is created then there is no problem
